version: '3'

services:
  crypto-fetcher:
    build: .
    image: crypto-fetcher:latest
    ports:
      - 3000:3000
    environment:
      - COINGECKO_BASEURL=https://api.coingecko.com/api/v3/
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
